export const skillsObj = {
    Slave: [  
        ["Cook/Servant",3,"Intrigue/4, Rhetoric/4, Cookery/4, Textilecraft/4, Herblore/2"],
        ["Farmer" , 4, "Agriculture/4, Weatherlore/4, Animalcraft/3"],   
        ["Herdsman", 2 ,"Animalcraft/4, Tracking/4, Survival/4, Weatherlore/4"],
        ["Gladiator", 4 , "Initiative/6, Three weapons at OML+SB×2, Unarmed/6, Physician/2"]
     ],

     Serf : [
        ["Cook/Servant",3,"Intrigue/4, Rhetoric/4, Cookery/4, Textilecraft/4, Herblore/2"],
        ["Farmer" , 4, "Agriculture/4, Weatherlore/4, Animalcraft/3"],   
        ["Herdsman", 2 ,"Animalcraft/4, Tracking/4, Survival/4, Weatherlore/4"],
     ],
     Unguilded: [
           ["Animal Trainer",3,"Animalcraft/4,Hidework/3,Riding/2"],
           ["Beggar", 1 , "Drawing/4, Mathematics/2, Script"],
           ["Cartographer/Artist", 5 ,"Drawing/4, Mathematics/2, Script"],
           ["Cleric/Shaman",3 , "Depends on deity. See CHaraCter 23"],
           ["Cook/Servant",3,"Intrigue/4, Rhetoric/4, Cookery/4, Textilecraft/4, Herblore/2"],
           ["Farmer" , 4, "Agriculture/4, Weatherlore/4, Animalcraft/3"],
           ["Fisherman",5 ,"Fishing/6, Seamanship/5, Weatherlore/4, Piloting/2, Shipwright/2"],
           ["Gladiator", 4, "Initiative/6, Three weapons at OML+SB×2, Unarmed/6, Physician/2"],
           ["Herdsman", 2, "Animalcraft/4, Tracking/4, Survival/4, Weatherlore/4"],
           ["Hunter/Trapper" , 5 , "Tracking/5, Three weapons at OML+SB, Stealth/4, Foraging/4, Survival/4, Hidework/3, Hunting/3, Fletching/2"],
           ["Laborer",1 ,"Intrigue/4"],
           ["Longshoreman", 1, "Intrigue/4, Seamanship/3"],
           ["Prostitute/Pimp",1 , "Lovecraft/4, Intrigue/4, Dagger/4"],
           ["Ratter", 3 , "Ratcraft/5, Dogcraft/4, Net/3, Club/5, Herblore/2"],
           ["Sage/Tutor", 5 ,"Folklore/5, Mathematics/2, 2nd Language, Two Scripts"],
           ["Scribe", 5, "Drawing/3, Mathematics/2, 2nd Language, Three Scripts"],
           ["Soldier",  4, "Depends on military unit type. See CHaraCter 27" ],
           ["Teamster", 2, "iding/4, Animalcraft/3, Whip/3, Woodcraft/3"],
           ["Thatcher", 4 , "Climbing/5, Woodcraft/4, Engineering/2"],
           ["Toymaker", 5 ,"Woodcraft/5, Lockcraft/3, Drawing/3, Hidework/3"]
     ],
     Guilded:[
        ["Alchemist", 7 ,"Alchemy/4, Mathematics/3, Herblore/3, Mining/2, Physician/2, Script"],
        ["Apothecary", 6 , "Herblore/4, Alchemy/2, Mathematics/2, Physician/2, Script"],
        ["Astrologer", 4 , "Astrology/4, Mathematics/3, Drawing/3, Tarotry/2, Script"],
        ["Chandler", 4 , "Three reasonable crafts at SB×3, Alchemy/2, Metalcraft/2, Script"],
        ["Charcoaler", 3 ,"Timbercraft/3, Survival/4, Woodcraft/3, Metalcraft/2"],
        ["Clothier", 6 , "Textilecraft/5, Hidework/4, Jewelcraft/3, Script"],
        ["Courtesan", 3 , "Lovecraft/5, Intrigue/5, Singing/5, Musician/3, Dancing/3, Script"],
        ["Embalmer", 7 , "Embalming/4, Woodcraft/3, Alchemy/2, Perfumery/2, Script"],
        ["Glassworker", 7 , "Glassworking/4, Ceramics/3, Alchemy/2, Script"],
        ["Harper/Skald", 7  ,"Singing/5, Folklore/5, Oratory/4, One instrument at Musician/4 and two at Musician/3, Woodcraft/3, Script"],
        ["Hideworker", 5 , "Hidework/5, Textilecraft/3, Alchemy/2"],
        ["Innkeeper",5, "Brewing/5, Cookery/4, Rhetoric/4, Intrigue/4, 2nd Language, Script"],
        ["Jeweler", 7 , "Jewelcraft/4, Metalcraft/3, Mining/2, Script"],
        ["Lexigrapher" , 5 , "Hidework (parchment/vellum)/5, Inkcraft/4, Drawing/3, Two Scripts"],
        ["Litigant", 7 , "Law/4, Oratory/5, Rhetoric/5, Intrigue/5, 2nd Language, Script"],
        ["Locksmith", 6 ,"Lockcraft/4, Metalcraft/3, Woodcraft/3, Script"],
        ["Mage (Shek-Pvar)", 7 , "Depends on Convocation. See CHaraCter 25"],
        ["Mason" , 7 , "Masonry/4, Woodcraft/4, Engineering/3, Mathematics/2, Script"],
        ["Mercantyler", 6 , "Rhetoric/5, Intrigue/5, Mathematics/3, Law/2, One weapon at OML, 2nd Language, Script"],
        ["Metalsmith" , 6 ,  "Metalcraft/4, Mining/2, Weaponcraft/2"],
        ["Miller/Millwright", 6 ,"Milling/4, Engineering/3, Agriculture/3, Script"],
        ["Miner", 6 , "Mining/4, Engineering/3, Woodcraft/3, Metalcraft/2, Jewelcraft/1"],
        ["Ostler", 5  , "Horsecraft/4, Riding/4, Hidework/4"],
        ["Perfumer", 6 , " Perfumery/4, Alchemy/3, Herblore/3, Embalming/2, Script"],
        ["Physician", 7 , "Physician/4, Herblore/3, Alchemy/3, Script"],
        ["Pilot", 9 , "Piloting/4, Weatherlore/5, Seamanship/4, Drawing/3, One weapon at OML, Shipwright/2, Mathematics/2, Script"],
        ["Potter", 6 , "Ceramics/5, Glassworking/2"],
        ["Salter", 4 , "Mining/3, Cookery/4, Survival/4, Fishing/4, Herblore/1"],
        ["Seaman", 5 , "Seamanship/5, Climbing/5, Club/5, Dagger/4, Fishing/4, Weatherlore/4, Piloting/2, Shipwright/2"],
        ["Shipwright", 7 ,"Shipwright/4, Woodcraft/4, Timbercraft/3, Metalcraft/2, Mathematics/2, Seamanship/3, Script"],
        ["Tentmaker", 5 ,"Textilecraft/4, Hidework/4, Woodcraft/2"],
        ["Thespian", 7 , "Acting/5, Oratory/4, Singing/4, Musician/3, Drawing/3"],
        ["Thief (Lia-Kavair)", 3 , "Legerdemain/4, Awareness/5, Stealth/4, Intrigue/4, Lockcraft/3, Club/5, Dagger/4, Acrobatics/3"],
        ["Timberwright", 6 ,"Timbercraft/4, Survival/4, Weatherlore/4, Woodcraft/3"],
        ["Weaponcrafter",7,"Weaponcraft/4, Two weapons at OML, Metalcraft/3, Fletching/3, Mining/2"],
        ["Woodcrafter",7 , "Woodcraft/5, Metalcraft/2, Hidework/3"]
      ],
  Nobility:[
    ["Herald", 5 , "Heraldry/4, Oratory/4, Rhetoric/4, Intrigue/5, Drawing/4, 2nd Language, Script (plus Knight skills to OML)"],
    ["Knight Bachelor" , 7 , "??????"],
    ["Knight/Bailiff",7 , "Knight Bachelor, plus Law/3, Agriculture/2."],
    ["Lady", 7 , "Intrigue/5, Folklore/4, Needlework/3, Dancing/3, Heraldry/3, Astrology/2, Drawing/3"]
 ]
}
